%%
%% This is file `uw-ece-workreport.cls',
%% generated with the docstrip utility.
%%
%% The original source files were:
%%
%% uw-wkrpt.dtx  (with options: `legacy-ece')
%% 
%% Copyright (C) 2002, 2003  Simon Law
%% 
%%   This program is free software; you can redistribute it and/or modify
%%   it under the terms of the GNU General Public License as published by
%%   the Free Software Foundation; either version 2 of the License, or
%%   (at your option) any later version.
%% 
%%   This program is distributed in the hope that it will be useful,
%%   but WITHOUT ANY WARRANTY; without even the implied warranty of
%%   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%%   GNU General Public License for more details.
%% 
%%   You should have received a copy of the GNU General Public License
%%   along with this program; if not, write to the Free Software
%%   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307  USA
%% 
\ClassWarning{uw-ece-workreport}{%
  The `uw-ece-workreport' class is now ^^J%
  deprecated.  Use `\string\usepackage[ece]{uw-wkrpt}' instead}
\DeclareOption*{\PassOptionsToClass {\CurrentOption}{uw-wkrpt}}
\ProcessOptions
\LoadClass[ece]{uw-wkrpt}
\newcommand{\UWECEWorkReportVersion}{2.0}
\endinput
%%
%% End of file `uw-ece-workreport.cls'.
